# Generated by Django 4.2.1 on 2023-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0013_alter_cryptocurrency1_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency2',
            name='response_data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency23',
            name='response_datA',
            field=models.JSONField(blank=True),
        ),
    ]
